# Change these first
owner: fingi # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Emenu OKKAMI
    url: https://emenu.okkami.com
  - name: Emenu OKKAMI Dhigu
    url: https://emenu.okkami.com/store?puid=000-000-0103&uid=0577867d-e617-4698-b651-e43ed3e78247
  
status-website:
  publish: true
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
