# Change these first
owner: fingi # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: CORE Production
    url: https://app.okkami.com
  - name: Emenu OKKAMI HTTP
    url: http://emenu.okkami.com/
  - name: Emenu OKKAMI HTTPS
    url: https://emenu.okkami.com/
  - name: Emenu OKKAMI Dhigu
    url: "https://emenu.okkami.com/api/store?puid=000-000-0103&uid=0577867d-e617-4698-b651-e43ed3e78247&k=null&type=Store&language=en"
    #__dangerous__body_down_if_text_missing: "currency_code"
    #__dangerous__disable_verify_peer: true
  - name: Emenu develop
    url: "https://emenu.develop.okkami.com:3443/store?puid=000-000-0011&uid=9b1825bb-7839-4266-9efd-9902f9f576f3"
  - name: OKKAMI Website
    url: http://www.okkami.com
    
status-website:
  publish: true
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**OKKAMI** uptime monitor and status page, powered entirely by GitHub."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
